# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCriarCadastro():
  def setup_method(self, method):
    self.driver = webdriver.Chrome('driver/Chrome/96/chromedriver.exe')
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_criarCadastro(self):
    self.driver.get("https://iterasys.com.br/cadastro/")
    self.driver.set_window_size(1540, 828)
    self.driver.find_element(By.ID, "nome").click()
    self.driver.find_element(By.ID, "nome").send_keys("Jose da Silva")
    self.driver.find_element(By.ID, "telefone").click()
    self.driver.find_element(By.ID, "telefone").send_keys("(11) 2345-6789")
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("tfcahoia@temporary-mail.net")
    self.driver.find_element(By.ID, "senha").click()
    self.driver.find_element(By.ID, "senha").send_keys("abc123")
    self.driver.find_element(By.ID, "e-captcha").click()
    self.driver.find_element(By.ID, "cadastro_form").click()
    self.driver.implicitly_wait(120)
    element = self.driver.find_element(By.ID, "btn_cadastro")
    self.driver.find_element(By.ID, "btn_cadastro").click()

  def test_efetuarLoginELogout(self):
    self.driver.get("https://iterasys.com.br/login/")
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("tfcahoia@temporary-mail.net")
    self.driver.find_element(By.ID, "senha").send_keys("abc123")
    self.driver.find_element(By.ID, "btn_login").click()
    #Pagina para completar o cadastro
    self.driver.get("https://iterasys.com.br/profile/")
    #EfetuarLogout
    self.driver.find_element(By.ID, "dropdownMenutopo").click()
    self.driver.find_element(By.LINK_TEXT, "Sair").click()




  
